### PR TITLE
Rename AS_923_925_TTN_AU.yml to AS_920_923_TTN_AU.yml

### PR DESCRIPTION
**Pull request by ama9910**
Australia uses AS_920_923 rather than AS_923_925, so renaming this file accordingly.

#### Summary
Australia's implementation of AS923 for TTN is on AS_920_923. When this file was created, it was anticipated that Australia may move to AS_923_925 when V3 was available, in order to support https://github.com/TheThingsNetwork/lorawan-stack/issues/1394. Since this may not happen, this file should refer to the current AS923 frequency plan in use in Australia.

#### Changes
Renamed file. Contents unchanged.

#### Notes for Reviewers
As discussed with @johanstokking 

#### Checklist

- [X] Scope: The referenced issue is addressed, there are no unrelated changes.
- [X] Compatibility: The changes are backwards compatible, they don't break existing deployments.
- [ ] Testing: The changes are tested.
*Note, change is not tested.
- [ ] Documentation: Relevant documentation is added or updated.
*Note, unsure if documentation exists elsewhere

### CODE REVIEW

**Review by johanstokking — CHANGES_REQUESTED** [review]
Thanks.

I'm afraid we need to keep the file, as these identifiers are strongly referenced by devices and gateways.

What needs to be done is;
1. Create a new file; `AS_920_923_TTN_AU`
2. Configure the right frequencies there
3. Add the file to the index
4. Update the description of the old one that is deprecated or something: https://github.com/TheThingsNetwork/lorawan-frequency-plans/blob/0899e7e22efe334321be0ab3331acfc98a08f3de/frequency-plans.yml#L172-L178

**Comment by johanstokking** [comment]
@ama9910 please also update the index `frequency-plans.yml`

**Comment by ama9910** [comment]
> @ama9910 please also update the index `frequency-plans.yml`

Yes I did. See second line of commit comments.

**Comment by johanstokking** [comment]
Did you push? I only see this here: https://github.com/TheThingsNetwork/lorawan-frequency-plans/pull/27/files

**Comment by ama9910** [comment]
Apologies, forgot to commit changes to frequency-plans.yml. Now committed/pushed.

**Review by htdvisser — APPROVED** [review]
Looks good to me 👍

**Review by johanstokking — APPROVED** [review]

**Pull request merged**
