### PR TITLE
Create new frequency plan for Viet Nam region

### PR DESCRIPTION
**Pull request by viethoa14**
band-id: AS_923
sub-bands:
- min-frequency: 920000000
  max-frequency: 923000000
duty-cycle: 0.01             # Duty cycle for this sub-band (optional; default: 1)
uplink-channels:
- frequency: 921400000
  min-data-rate: 0
  max-data-rate: 5
  radio: 0
- frequency: 921600000
  min-data-rate: 0
  max-data-rate: 5
  radio: 0
- frequency: 921800000
  min-data-rate: 0
  max-data-rate: 5
  radio: 0
- frequency: 922000000
  min-data-rate: 0
  max-data-rate: 5
  radio: 0
- frequency: 922200000
  min-data-rate: 0
  max-data-rate: 5
  radio: 0
- frequency: 922400000
  min-data-rate: 0
  max-data-rate: 5
  radio: 1
- frequency: 922600000
  min-data-rate: 0
  max-data-rate: 5
  radio: 1
- frequency: 922800000
  min-data-rate: 0
  max-data-rate: 5
  radio: 1
downlink-channels:
- frequency: 921400000
  min-data-rate: 0
  max-data-rate: 5
- frequency: 921600000
  min-data-rate: 0
  max-data-rate: 5
- frequency: 921800000
  min-data-rate: 0
  max-data-rate: 5
- frequency: 922000000
  min-data-rate: 0
  max-data-rate: 5
- frequency: 922200000
  min-data-rate: 0
  max-data-rate: 5
- frequency: 922400000
  min-data-rate: 0
  max-data-rate: 5
- frequency: 922600000
  min-data-rate: 0
  max-data-rate: 5
- frequency: 922800000
  min-data-rate: 0
  max-data-rate: 5

lora-standard-channel:
  frequency: 923000000
  data-rate: 6
  radio: 1
#fsk-channel:
#frequency: 921200000
#data-rate: 7
#radio: 0
radios:
- enable: true
  chip-type: SX1257
  frequency: 921800000
  rssi-offset: -166
  tx:
    min-frequency: 920000000
    max-frequency: 923000000
- enable: true
  chip-type: SX1257
  frequency: 922800000
  rssi-offset: -166
clock-source: 1
rx2-channel:                   # Rx2 channel (optional)
  frequency: 921400000
  min-data-rate: 0
  max-data-rate: 5
  radio: 0
max-eirp: 16

#### Summary

Now on Viet Nam we are using AS_920_923 with two frequency default 921.4 (rx2) and 921.6, so we can not use frequency plan AS_923 on TTN system. We need TTN create new frequency plan for VN region, it should AS_920_923_TTN_VN. 
...

#### Changes

- Create new frequency plan (AS_920_923_TTN_VN)
- Two frequencies default, that is used by end-devices 921.4 (rx2) and 921.6 

#### Notes for Reviewers

...

#### Checklist

- [ ] Scope: The referenced issue is addressed, there are no unrelated changes.
- [ ] Compatibility: The changes are backwards compatible, they don't break existing deployments.
- [ ] Testing: The changes are tested.
- [ ] Documentation: Relevant documentation is added or updated.

### CODE REVIEW

**Comment by johanstokking** [comment]
@viethoa14 thanks. I don't really understand the PR here; you're not proposing new files but rather merge `master` into an outdated feature branch `feature/5-as923`, right?

Do you need help with filing a pull request for the Viet Nam frequency plan?

**Comment by viethoa14** [comment]
Thanks for your support!

I have tried create new request for Viet Nam frequency plan, i have choose created "pull request" but it was not ok. Maybe i didn't follow correct procedure. Sorry for this inconvenience.
Please push new request for Viet Nam frequency plan. Thanks

**Comment by johanstokking** [comment]
@viethoa14 please see https://docs.github.com/en/github/collaborating-with-issues-and-pull-requests/creating-a-pull-request-from-a-fork for help

**Comment by johanstokking** [comment]
Closing this one

**Pull request closed without merging**
